#name: Public Frontend
#run-name: ${{ github.actor }} is deploying
#on:
#  push:
#    branches: [staging, main]
#jobs:
#  init_step:
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - name: prettier
#        run: |
#          echo 'called from main.yml'
#  shared_workflow_2:
#    uses: ./.github/workflows/shared_steps.yml
#    secrets: inherit
#    with:
#      stage: 'staging'
