export { default as VisualizeDataPage } from './visualizeData'
export { default as IntegrateDataPage } from './integrateData'
export { default as LeverageTheCloudPage } from './leverageTheColud'
export { default as EndToEndSolutionsPage } from './endToEndSolutions'
export { default as GovernancePage } from './governance'
export { default as SecurityPage } from './securityPage'
export { default as PlatformOverviewPage } from './overview'
